# Generated by Django 5.1.4 on 2024-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_behaviorlog_note_teacher_alter_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('end_of_school_time', models.TimeField(default='15:00')),
            ],
        ),
    ]
